name: CI


on:
  pull_request:
  push:
    branches:
      - master

jobs:
  mix_test:
    name: Test
    runs-on:
      - runs-on
      - runner=2cpu-linux-x64
      - "run-id=${{ github.run_id }}"
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Setup mise
        uses: step-security/mise-action@2796166110dee826668caddd4bffedae5116e7cd # v4.2.0

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - run: mix test

  mix_credo:
    name: Run credo
    runs-on:
      - runs-on
      - runner=2cpu-linux-x64
      - "run-id=${{ github.run_id }}"
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Setup mise
        uses: step-security/mise-action@2796166110dee826668caddd4bffedae5116e7cd # v4.2.0

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - run: mix credo --strict

  check_formatted:
    name: Check formatted
    runs-on:
      - runs-on
      - runner=2cpu-linux-x64
      - "run-id=${{ github.run_id }}"
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Setup mise
        uses: step-security/mise-action@2796166110dee826668caddd4bffedae5116e7cd # v4.2.0

      - run: mix format --check-formatted
